# Ensure that Milestone 1 is ran, installs and setups DHCP
# Version 0.1

# Setup DHCP
- name: Configure DHCP
  hosts: localhost
  connection: local
  tasks:
  - name: Run dhcp configure script
    ansible.builtin.shell: bash ~/Solid-Tortoise-Final-Project/dhcp_script.sh

# Ensure DHCP is running
- name: Ensure myservice  is in a running state
  hosts: dhcp01,dhcp02
  service:
    name: dhcpd
    state: started
  register: dhcp_start
  until: dhcp_start.status.ActiveState == "active"
  retries: 50
  delay: 10

# Workstation setup for DHCP
- name: Set Windows workstations to use DHCP
  hosts: wks01,wks02
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    ansible_shell_type: powershell
  tasks:
   - name: Set workstations to get new DNS
     ansible.windows.win_dns_client:
       adapter_names: 'Ethernet*'
       dns_servers: []

   - name: Refresh DNS
     ansible.windows.win_shell: ipconfig /release; ipconfig /renew