# Adds DNS records, safe to rerun
# Version 0.1
task:
- hosts: all
  vars:
    ansible_user: Kurma
    ansible_password: HailTheTurtle345
    ansible_shell_type: powershell

- name: Create primary dns zone
  community.windows.win_dns_zone:
    name: tortoise.local
    replication: domain
    type: primary
    state: present

- name: Create reverse-lookup zone
  community.windows.win_dns_zone:
    name: 172.16.1-addr.arpa
    replication: domain
    type: primary
    state: present

- name: Create mgmt01 A record
  community.windows.win_dns_record:
    name: "mgmt01"
    type: "A"
    value: "172.16.1.14"
    zone: "tortoise.local"

- name: Create ad01 A record
  community.windows.win_dns_record:
    name: "ad01"
    type: "A"
    value: "172.16.1.12"
    zone: "tortoise.local"

- name: Create mgmt01 PTR record
  community.windows.win_dns_record:
    name: "172.16.1.14"
    type: "PTR"
    value: "mgmt01"
    zone: "172.16.1-addr.arpa"

- name: Create ad01 PTR record
  community.windows.win_dns_record:
    name: "172.16.1.12"
    type: "PTR"
    value: "ad01"
    zone: "172.16.1-addr.arpa"