# This playbook fully setups DOCKER

- hosts: docker
  become: true
  tasks:
    - name: Install prereqs
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      state: present
      update_cache: true

    - name: Add Dockers GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: true
    # The "|" indicates multiline commands
    - name: Install docker-compose
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        cat << EOF > .env
        OWNCLOUD_VERSION=10.9
        OWNCLOUD_DOMAIN=localhost:8080
        ADMIN_USERNAME="{{ owncloud_user }}"
        ADMIN_PASSWORD="{{ owncloud_password }}"
        HTTP_PORT=8080
        EOF
    
    - name: Prep owncloud
       ansible.builtin.shell: |
          mkdir owncloud-docker-server
          cd owncloud-docker-server
          wget https://raw.githubusercontent.com/owncloud/docs-server/master/modules/admin_manual/examples/installation/docker/docker-compose.yml
          
      
    - name: Install 'owncloud_compose.yml'
      community.docker.docker_compose:
        # Needs full path
        project_src: owncloud_compose
      register: output

    - ansible.builtin.debug:
        var: output
