# Setup for domain, adds mgmt01 to domain
# Maybe add ability to automatically add other machines? (Like trigger another playbook with variables?)
# Version: 0.5
- name: Install Active Directory
  hosts: ad01
  tasks:
  - name: Install Active Directory Domain Services on ad01
    win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      state: present
    register: domain_state
  
  - name: Reboot
    ansible.windows.win_reboot:
    when: domain_state.reboot_required

  - name: Create new domain in a new forest on ad01
    win_domain:
      install_dns: yes
      dns_domain_name: tortoise.local
      safe_mode_password: Shmear69420
    register: domain_state

  - name: Reboot
    ansible.windows.win_reboot:
    when: domain_state.reboot_required

- name: Make Domain users
  tasks:
  - name: Create domain admin user "Kurma"
    win_domain_user:
      domain_server: ad01.tortoise.local
      name: Kurma
      password: HailTheTurtle345
      password_never_expires: yes
      group_action: add
      groups:
        - domain admins
      state: present

- name: Add computers to domain
  hosts: mgmt01
  tasks:
    - name: Add mgmt01 to Domain
      win_domain_membership:
        dns_domain_name: tortoise.local
        hostname: mgmt01
        domain_admin_user: Kurma
        domain_admin_password: enterpass
        state: domain
      register: host_restart

    - name: Reboot
      ansible.windows.win_reboot:
      when: domain_state.reboot_required

- name: Add DNS records
  hosts: all
  vars:
    ansible_user: Kurma
    ansible_password: HailTheTurtle345
    ansible_shell_type: powershell
  tasks:
  - name: Create primary dns zone
    community.windows.win_dns_zone:
      name: tortoise.local
      replication: domain
      type: primary
      state: present

  - name: Create reverse-lookup zone
    community.windows.win_dns_zone:
      name: 172.16.1-addr.arpa
      replication: domain
      type: primary
      state: present

  - name: Create mgmt01 A record
    community.windows.win_dns_record:
      name: "mgmt01"
      type: "A"
      value: "172.16.1.14"
      zone: "tortoise.local"

  - name: Create ad01 A record
    community.windows.win_dns_record:
      name: "ad01"
      type: "A"
      value: "172.16.1.12"
      zone: "tortoise.local"

  - name: Create mgmt01 PTR record
    community.windows.win_dns_record:
      name: "172.16.1.14"
      type: "PTR"
      value: "mgmt01"
      zone: "172.16.1-addr.arpa"

  - name: Create ad01 PTR record
    community.windows.win_dns_record:
      name: "172.16.1.12"
      type: "PTR"
      value: "ad01"
      zone: "172.16.1-addr.arpa"