# Setup for domain, adds mgmt01 to domain, must run ComToDomain.yml to add other computers
# Maybe add ability to automatically add other machines? (Like trigger ComToDomain.yml with variables?)
# Version: 0.1
become: yes
become_method: enable
tasks:
- name: Install Active Directory Domain Services on ad01
  hosts: ad01
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    state: present

- name: Create new domain in a new forest on ad01
  hosts: ad01
  win_domain:
    dns_domain_name: tortoise.local
    safe_mode_password: Shmear69420

- name: Reboot
  win_reboot:
    when: domain_state.reboot_required

- name: Create domain admin user "Kurma"
  hosts: ad01
  win_domain_user:
    name: Kurma
    password: HailTheTurtle345
    password_never_expires: yes
    group_action: add
    groups:
      - domain admins
    state: present

- name: Add computers to domain
  # ONLY CONFIGURED FOR MGMT01 CURRENTLY
  hosts: mgmt01
  win_domain_membership:
    dns_domain_name: tortoise.local
    hostname: mgmt01
    domain_admin_user: Kurma
    domain_admin_password: enterpass
    state: domain

- name: Reboot
  win_reboot:
    when: domain_state.reboot_required