# Ansible RDP GPO MGMT01
# Solid-Tortoise
# CAN'T RUN TWICE!!!
# v 0.1

- name: mgmt01 install group policy management
  hosts: mgmt01- name: Ensure the group Cow doesn't exist using the Distinguished Name
  community.windows.win_domain_group:
    name: CN=Cow,OU=groups,DC=ansible,DC=local
    state: absent
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    ansible_shell_type: powershell
  tasks:
    - name: "Install GPMC"
      ansible.windows.win_feature:
         name: 
         - GPMC
         state: present 
      register: host_restart
      
    - name: Reboot
      ansible.windows.win_reboot:
      when: host_restart.reboot_required

- name: dc01 rdp setup
  hosts: dc01
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    become: yes
    ansible_shell_type: powershell
  tasks:
  - name: make rdp ou
    ansible.windows.win_shell: New-ADOrganizationalUnit -Name 'rdp' -Path 'DC=tortoise,DC=local' -ProtectedFromAccidentalDeletion $False
  - name: move wks01&02 to rdp ou
    ansible.windows.win_shell: |
      Move-ADObject –Identity 'CN=wks01,CN=Computers,DC=tortoise,DC=local' -TargetPath 'OU=rdp,DC=tortoise,DC=local'
      Move-ADObject –Identity 'CN=wks02,CN=Computers,DC=tortoise,DC=local' -TargetPath 'OU=rdp,DC=tortoise,DC=local'
  - name: make RDPallow gpo attached to 
    ansible.windows.win_shell: New-GPO -name RDPallow | new-gplink -target 'ou=rdp,dc=tortoise,dc=local'
  - name: change regvalue for rdp
    ansible.windows.win_shell: Set-GPRegistryValue -Name 'RDPallow' -Key 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -ValueName 'fDenyTSConnections' -Value 0
