# Some information will need to be placed in all.yml
# Needs to be run with the command "ansible-playbook -i domain_install_inventory.txt <PLACEHOLDER FOR PATH TO PLAYBOOK>", depending on vault or not add "--ask-vault-pass"

# This file plays the needed playbooks in order to complete the requirments for Milestone 1

- name: Play "Domain_install"
  import_playbook: Domain_install.yaml

- name: Play "DNS_Additions"
  import_playbook: DNS_Additions.yaml

- name: Add_Domain_Computers
  import_playbook: Add_Domain_Computers.yaml