# Some information will need to be placed in all.yml
# Needs to be run with the command "ansible-playbook -i inventory.txt <PLACEHOLDER FOR PATH TO PLAYBOOK>", depending on vault or not add "--ask-vault-pass"

# This file plays the needed playbooks in order to complete the requirments for Milestone 2
# Version 1.0

- name: Play "Reqs"
  import_playbook: Reqs.yaml

- name: Play "Install_Apps"
  import_playbook: Install_Apps_M2.yaml

- name: Play "DHCP_Setup"
  import_playbook: DHCP_Setup_M2.yaml

- name: Play "UTIL"
  import_playbook: UTIL.yaml