# Installs all needed prerequsites for milestones
# Version 0.1

- name: Install prereqs
  hosts: localhost
  connection: local
  tasks:
  - name: Install collection 'ansible.windows'
    community.general.ansible_galaxy_install:
      type: collection
      name: ansible.windows

  - name: Install collection 'community.windows'
    community.general.ansible_galaxy_install:
      type: collection
      name: community.windows
  
- name: Set Windows Timezones to 'Eastern Standard Time'
  hosts: windows
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    ansible_shell_type: powershell
  community.windows.win_timezone:
    timezone: Eastern Standard Time
  
- name: Set Linux Timezones to 'America/New_York'
  hosts: linux
  community.general.timezone:
    name: America/New_York