# Installs all needed prerequsites for milestones, (WINDOWS WORKSTATIONS MAY FAIL IF NOT IN DOMAIN)
# Version 1.0

- name: Install prereqs
  hosts: localhost
  connection: local
  tasks:
  - name: Install collection 'ansible.windows'
    community.general.ansible_galaxy_install:
      type: collection
      name: ansible.windows

  - name: Install collection 'community.windows'
    community.general.ansible_galaxy_install:
      type: collection
      name: community.windows

  - name: Install collection 'community.docker'
    community.general.ansible_galaxy_install:
      type: collection
      name: community.docker

# Any failures in this and the linux sections "gathering" phase is fine since it most likely means the computer just isn't on :) (OR NOT IN THE DOMAIN)
- name: Set Windows Timezones to 'Eastern Standard Time'
  hosts: windows
  vars:
    ansible_user: "Administrator"
    ansible_shell_type: powershell
  tasks:
    - community.windows.win_timezone:
        timezone: Eastern Standard Time
  
- name: Set Linux Timezones to 'America/New_York'
  hosts: linux
  become: true
  tasks:
    - community.general.timezone:
        name: America/New_York