# Installs all needed prerequsites for milestones
# Version 0.1

- name: Install prereqs
  hosts: localhost
  connection: local
  tasks:
  - name: Install collection 'ansible.windows'
    community.general.ansible_galaxy_install:
      type: collection
      name: ansible.windows

  - name: Install collection 'community.windows'
    community.general.ansible_galaxy_install:
      type: collection
      name: community.windows
  
  - name: Install collection 'community.general'
    community.general.ansible_galaxy_install:
      type: collection
      name: community.general
  
- name: Set Windows Timezones
  hosts: windows
  community.windows.win_timezone:
    timezone: Eastern Standard Time
  
- name: Set Linux Timezones
  hosts: linux
  community.general.timezone:
    name: America/New_York