# Download wallpaper onto MGMT01

- name: Download WP
  hosts: mgmt01
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    ansible_shell_type: powershell
  tasks:
  - name: Download Wallpaper
    ansible.windows.win_get_url:
      url: https://github.com/Oliver-Mustoe/Solid-Tortoise-Final-Project/raw/Unsolid-Tortoise/Wallpaper.jpg
      dest: \\tortoise.local\shell_share\shell_share_user\background.jpg