# create OU and setup wallpaper
# Solid-Tortoise
# CAN'T RUN TWICE!!!
# v 0.1

- name: dc01 rdp setup
  hosts: dc01
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    ansible_shell_type: powershell
  tasks:
  - name: Make wallpaper ou
    ansible.windows.win_shell: New-ADOrganizationalUnit -Name 'wallpaper' -Path 'DC=tortoise,DC=local' -ProtectedFromAccidentalDeletion $False
  - name: Move MGMT01 to wallpaper
    ansible.windows.win_shell: Move-ADObject –Identity 'CN=MGMT01,CN=Computers,DC=tortoise,DC=local' -TargetPath 'OU=wallpaper,DC=tortoise,DC=local'
  - name: Download Wallpaper
    ansible.windows.win_shell: Invoke-WebRequest -URI 'https://github.com/Oliver-Mustoe/Solid-Tortoise-Final-Project/raw/Unsolid-Tortoise/Wallpaper.jpg' -OutFile 'C:\background.jpg'
  - name: Make wallpaperSet GPO
    ansible.windows.win_shell: New-GPO -name 'wallpaperSet'
  - name: Change regvalue for wallpaperSet
    ansible.windows.win_shell: Set-GPRegistryValue -Name 'WP_ICT' -key 'HKCU:\Control Panel\Desktop\' -ValueName 'Wallpaper' -type String -value 'C:\background.jpg'
  - name: Link GPO
    ansible.windows.win_shell: New-GPLink -name 'wallpaperSet' -target 'OU=wallpaper,dc=tortoise,dc=local' 
