# Ansible RDP GPO
# Solid-Tortoise
# v 0.1

- name: RDP wks01 & wks02
  hosts: wks01,wks02
  vars:
    ansible_user: "{{ domain_admin_1_user }}"
    ansible_shell_type: powershell
  tasks:
  - name: Allow RDP
    ansible.windows.win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
